### ISSUE TITLE
Do we know whatever the dustbin will appear after picking 2nd one?

### ISSUE THREAD

**Issue by buraktamturk** [serrestech/hackathon#12]
In Part B of the problem:

'Assume the same as before, but after you picked up the second dustbin, dustbins also appear in "A. Kamila" and "K. Mitrousi"'.

Do the driver know that these dustbins will (or possibly) appear before starting his/her trip? So, this driver could start visiting the dustbins near to these locations?

**Comment by buraktamturk** [comment]
I figured it out, the previous rule which is limits dustbins to 4 villages is still applied. So, they don't know.

**Comment by theodorosploumis** [comment]
Yes, the driver learns about it after picking up the dustbins in "A. Kamila" and "K. Mitrousi"'.
